/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_management.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import student_management.controller.ForgotPassController;
import student_management.entities.User;

/**
 *
 * @author GIANG
 */
public class ForgotPassView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView1
     */
    private Integer randomCode;
    private Component component;

    public ForgotPassView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        forgotPassPanel = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        verifyLabel = new javax.swing.JLabel();
        sendCodeBtn = new javax.swing.JButton();
        errorForgot = new javax.swing.JTextField();
        header4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        exitMouse = new javax.swing.JButton();
        verifyField = new javax.swing.JTextField();
        notifycationForgot = new javax.swing.JTextField();
        notifycationForgot1 = new javax.swing.JTextField();
        resetPasswordPanel = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        exitMouseReset = new javax.swing.JButton();
        confirmPassField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordLabel = new javax.swing.JLabel();
        errorPasswordField = new javax.swing.JTextField();
        errorConfirmPassField = new javax.swing.JTextField();
        notifycationReset = new javax.swing.JTextField();
        navigationPanel = new javax.swing.JPanel();
        nextBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainPanel1.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        MainPanel1.setForeground(new java.awt.Color(0, 153, 153));

        mainPanel.setLayout(new java.awt.CardLayout());

        forgotPassPanel.setBackground(new java.awt.Color(255, 255, 255));

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLabel.setText("Email");

        verifyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        verifyLabel.setText("Verify Code");

        sendCodeBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sendCodeBtn.setForeground(new java.awt.Color(102, 102, 102));
        sendCodeBtn.setText("Send Code");
        sendCodeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendCodeBtn.setFocusPainted(false);
        sendCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCodeBtnActionPerformed(evt);
            }
        });

        errorForgot.setEditable(false);
        errorForgot.setBackground(new java.awt.Color(255, 255, 255));
        errorForgot.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        errorForgot.setForeground(new java.awt.Color(255, 0, 0));
        errorForgot.setBorder(null);
        errorForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorForgotActionPerformed(evt);
            }
        });

        header4.setBackground(new java.awt.Color(153, 255, 255));
        header4.setForeground(new java.awt.Color(204, 204, 204));
        header4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Forgot Password");

        exitMouse.setBackground(new java.awt.Color(153, 255, 255));
        exitMouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_32px.png"))); // NOI18N
        exitMouse.setBorder(null);
        exitMouse.setBorderPainted(false);
        exitMouse.setContentAreaFilled(false);
        exitMouse.setFocusPainted(false);
        exitMouse.setOpaque(true);
        exitMouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseMouseExited(evt);
            }
        });
        exitMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header4Layout = new javax.swing.GroupLayout(header4);
        header4.setLayout(header4Layout);
        header4Layout.setHorizontalGroup(
            header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header4Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header4Layout.setVerticalGroup(
            header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
            .addComponent(exitMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        notifycationForgot.setEditable(false);
        notifycationForgot.setBackground(new java.awt.Color(255, 255, 255));
        notifycationForgot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notifycationForgot.setForeground(new java.awt.Color(51, 51, 255));
        notifycationForgot.setBorder(null);
        notifycationForgot.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        notifycationForgot.setEnabled(false);
        notifycationForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifycationForgotActionPerformed(evt);
            }
        });

        notifycationForgot1.setEditable(false);
        notifycationForgot1.setBackground(new java.awt.Color(255, 255, 255));
        notifycationForgot1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notifycationForgot1.setForeground(new java.awt.Color(51, 51, 255));
        notifycationForgot1.setBorder(null);
        notifycationForgot1.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        notifycationForgot1.setEnabled(false);
        notifycationForgot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifycationForgot1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forgotPassPanelLayout = new javax.swing.GroupLayout(forgotPassPanel);
        forgotPassPanel.setLayout(forgotPassPanelLayout);
        forgotPassPanelLayout.setHorizontalGroup(
            forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(forgotPassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorForgot)
                    .addGroup(forgotPassPanelLayout.createSequentialGroup()
                        .addGroup(forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel)
                            .addComponent(verifyLabel))
                        .addGap(14, 14, 14)
                        .addGroup(forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sendCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verifyField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(forgotPassPanelLayout.createSequentialGroup()
                        .addGroup(forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notifycationForgot, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notifycationForgot1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))))
        );
        forgotPassPanelLayout.setVerticalGroup(
            forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotPassPanelLayout.createSequentialGroup()
                .addComponent(header4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(notifycationForgot, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendCodeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notifycationForgot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(forgotPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorForgot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        mainPanel.add(forgotPassPanel, "card2");

        resetPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(153, 255, 255));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged1(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed1(evt);
            }
        });

        headerLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        headerLabel.setText("Reset Password");

        exitMouseReset.setBackground(new java.awt.Color(153, 255, 255));
        exitMouseReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_32px.png"))); // NOI18N
        exitMouseReset.setBorder(null);
        exitMouseReset.setBorderPainted(false);
        exitMouseReset.setContentAreaFilled(false);
        exitMouseReset.setFocusPainted(false);
        exitMouseReset.setOpaque(true);
        exitMouseReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseResetMouseExited(evt);
            }
        });
        exitMouseReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMouseResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addGap(93, 93, 93)
                .addComponent(exitMouseReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLabel)
            .addComponent(exitMouseReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        passwordLabel.setText("New Password");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        confirmPasswordLabel.setText("Confirm Password");

        errorPasswordField.setEditable(false);
        errorPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        errorPasswordField.setForeground(new java.awt.Color(255, 0, 0));
        errorPasswordField.setBorder(null);

        errorConfirmPassField.setEditable(false);
        errorConfirmPassField.setBackground(new java.awt.Color(255, 255, 255));
        errorConfirmPassField.setForeground(new java.awt.Color(255, 0, 0));
        errorConfirmPassField.setBorder(null);

        notifycationReset.setEditable(false);
        notifycationReset.setBackground(new java.awt.Color(255, 255, 255));
        notifycationReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notifycationReset.setForeground(new java.awt.Color(51, 51, 255));
        notifycationReset.setBorder(null);
        notifycationReset.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        notifycationReset.setEnabled(false);
        notifycationReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifycationResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resetPasswordPanelLayout = new javax.swing.GroupLayout(resetPasswordPanel);
        resetPasswordPanel.setLayout(resetPasswordPanelLayout);
        resetPasswordPanelLayout.setHorizontalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addComponent(notifycationReset, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorPasswordField)
                    .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                        .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLabel)
                            .addComponent(confirmPasswordLabel))
                        .addGap(60, 60, 60)
                        .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmPassField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(passwordField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(errorConfirmPassField))
                .addContainerGap())
        );
        resetPasswordPanelLayout.setVerticalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(notifycationReset, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        mainPanel.add(resetPasswordPanel, "card2");

        nextBtn.setBackground(new java.awt.Color(255, 255, 255));
        nextBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nextBtn.setText("Next >");
        nextBtn.setToolTipText("Next to step");
        nextBtn.setFocusPainted(false);
        nextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextBtnMouseExited(evt);
            }
        });
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        cancelBtn.setText("Close");
        cancelBtn.setToolTipText("Cancel");
        cancelBtn.setFocusPainted(false);
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnMouseExited(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        backBtn.setText("< Back");
        backBtn.setToolTipText("Back to Login");
        backBtn.setFocusPainted(false);
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        finishBtn.setBackground(new java.awt.Color(255, 255, 255));
        finishBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        finishBtn.setText("Finish");
        finishBtn.setToolTipText("Next to step");
        finishBtn.setActionCommand("");
        finishBtn.setFocusPainted(false);
        finishBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finishBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finishBtnMouseExited(evt);
            }
        });
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextBtn)
                .addGap(18, 18, 18)
                .addComponent(finishBtn)
                .addGap(36, 36, 36)
                .addComponent(cancelBtn)
                .addContainerGap())
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn)
                    .addComponent(cancelBtn)
                    .addComponent(backBtn)
                    .addComponent(finishBtn))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanel1Layout = new javax.swing.GroupLayout(MainPanel1);
        MainPanel1.setLayout(MainPanel1Layout);
        MainPanel1Layout.setHorizontalGroup(
            MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navigationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanel1Layout.setVerticalGroup(
            MainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanel1Layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendCodeBtnActionPerformed

    }//GEN-LAST:event_sendCodeBtnActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
        header4.setCursor(new Cursor(13));
    }//GEN-LAST:event_headerMouseDragged

    private void exitMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseActionPerformed

    private void exitMouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMouseEntered
        exitMouse.setBackground(new Color(228, 38, 69));

    }//GEN-LAST:event_exitMouseMouseEntered

    private void exitMouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMouseExited
        exitMouse.setBackground(new Color(153, 255, 255));

    }//GEN-LAST:event_exitMouseMouseExited

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void nextBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseEntered
//        nextBtn.setContentAreaFilled(true);
//        nextBtn.setBorderPainted(true);
//        nextBtn.setBorder(new LineBorder(Color.BLUE));
//        nextBtn.setBackground(new Color(204, 204, 204));

    }//GEN-LAST:event_nextBtnMouseEntered

    private void nextBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseExited
//        nextBtn.setContentAreaFilled(false);
//        nextBtn.setBorderPainted(false);

    }//GEN-LAST:event_nextBtnMouseExited

    private void headerMouseDragged1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged1
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
        header.setCursor(new Cursor(13));
    }//GEN-LAST:event_headerMouseDragged1

    private void headerMousePressed1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed1
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerMousePressed1

    private void notifycationForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifycationForgotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notifycationForgotActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    private void cancelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnMouseEntered

    private void cancelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnMouseExited

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void finishBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_finishBtnMouseEntered

    private void finishBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_finishBtnMouseExited

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishBtnActionPerformed

    private void notifycationResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifycationResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notifycationResetActionPerformed

    private void notifycationForgot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifycationForgot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notifycationForgot1ActionPerformed

    private void exitMouseResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseResetMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseResetMouseEntered

    private void exitMouseResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseResetMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseResetMouseExited

    private void exitMouseResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMouseResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseResetActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void errorForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorForgotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorForgotActionPerformed
    int xx;
    int xy;


    public void addExitMouseListener(ActionListener listener) {
        exitMouse.addActionListener(listener);    
        cancelBtn.addActionListener(listener);
        exitMouseReset.addActionListener(listener);
    }

    public void addSendVerifyCodeListener(ActionListener listener) {
        sendCodeBtn.addActionListener(listener);
    }

 

    public void addNextToStepListener(ActionListener listener) {
        nextBtn.addActionListener(listener);
    }

    public void addFinishListener(ActionListener listener) {
        finishBtn.addActionListener(listener);
    }
      public void addBackToForgotListener(ActionListener listener) {
          backBtn.addActionListener(listener);
        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField errorConfirmPassField;
    private javax.swing.JTextField errorForgot;
    private javax.swing.JTextField errorPasswordField;
    private javax.swing.JButton exitMouse;
    private javax.swing.JButton exitMouseReset;
    private javax.swing.JButton finishBtn;
    private javax.swing.JPanel forgotPassPanel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header4;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField notifycationForgot;
    private javax.swing.JTextField notifycationForgot1;
    private javax.swing.JTextField notifycationReset;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel resetPasswordPanel;
    private javax.swing.JButton sendCodeBtn;
    private javax.swing.JTextField verifyField;
    private javax.swing.JLabel verifyLabel;
    // End of variables declaration//GEN-END:variables

    public void startLogin(Component component) {
        this.setVisible(true);
        this.setLocationRelativeTo(component);
        this.showForgotView();

    }

    public Component setViewPosition(Component component) {
        return component;
    }

    public void showResetView() {
        resetPasswordPanel.setVisible(true);
        clearResetView();
        enableBackBtn();
        disableNextBtn();
        enableFinishBtn();

    }

    public void hideResetView() {
        resetPasswordPanel.setVisible(false);
    }

    public void showForgotView() {
        forgotPassPanel.setVisible(true);
        clearForgotView();
        disableFinishBtn();
        disableBackBtn();
        disableNextBtn();
       
        showNotify("Please enter your email!");
    }
    public void backToForgotView(){
    forgotPassPanel.setVisible(true);       
        disableFinishBtn();
        disableBackBtn();     
   
        disableSendCodeBtn();
    }

  

    public void hideForgotView() {
        forgotPassPanel.setVisible(false);
    }

    public void close() {
        this.setVisible(false);

    }

    public void clearForgotView() {
        verifyField.setText("");
        errorForgot.setText("");
        notifycationForgot.setText("");

    }

    public void clearResetView() {
        passwordField.setText("");
        confirmPassField.setText("");
        errorPasswordField.setText("");
        errorConfirmPassField.setText("");
        notifycationReset.setText("");
    }

    public String getEmailField() {
        return emailField.getText();

    }

    public String getVerifyCodeField() {
        return verifyField.getText();

    }

    public String getConfirmPassField() {
        return String.valueOf(confirmPassField.getPassword());
    }

    public String getPasswordField() {
        return String.valueOf(passwordField.getPassword());
    }

    public void showErrorConfirmPass(String errorConfirmPass) {
        errorConfirmPassField.setText(errorConfirmPass);

    }

    public void showErrorPassword(String errorPassword) {
        errorPasswordField.setText(errorPassword);
    }

    public void disableSendCodeBtn() {
        sendCodeBtn.setEnabled(false);
        sendCodeBtn.setBackground(new Color(240, 240, 240));
    }

    public void enableSendCodeBtn() {
        sendCodeBtn.setEnabled(true);
    }

    public void disableNextBtn() {
        nextBtn.setEnabled(false);

    }

    public void enableNextBtn() {
        this.nextBtn.setEnabled(true);
    }

    public void disableFinishBtn() {
        finishBtn.setEnabled(false);
    }

    public void enableFinishBtn() {
        finishBtn.setEnabled(true);
    }

    public void disableBackBtn() {
        backBtn.setEnabled(false);
    }

    public void enableBackBtn() {
        backBtn.setEnabled(true);
    }

   

    

    public void disableEmailField() {
        this.emailField.setEnabled(false);
    }

    public void showError(String error) {
        errorForgot.setText(error);

    }
    
    public void showNotify(String message) {
        notifycationForgot.setText(message);
    }

    public void showNotify1(String message) {
        notifycationForgot1.setText(message);
    }

    public Boolean checkVerifyCode(User user) {
        int code = 0;
        try {
            code = Integer.parseInt(verifyField.getText());
        } catch (NumberFormatException e) {
            return false;
        }
        return (user.getEmail().equals(emailField.getText()) && code == user.getVerifyCode());

    }

    public void deleteError() {
        errorForgot.setText("");
    }

    public boolean regexEmail(String email) {
        String regexEmail = "^\\w+([+.-]\\w+)*@\\w+([.-]\\w+)*[.]\\w+([.-]\\w+)*$";
        Pattern p = Pattern.compile(regexEmail);
        Matcher matcher = p.matcher(email);
        
        return matcher.matches();
    }

    public boolean regexVerifyCode(String code) {
        String regexCode = "^[\\d]{6}$";
        Pattern p = Pattern.compile(regexCode);
        Matcher matcher = p.matcher(code);
        return matcher.matches();
    }

    public boolean regexNewPassword(String pass) {
        String regexCode = "^(?=.*[A-Z])(?=.*\\d)(?=.*[a-z])[A-Za-z0-9]{8,}$";
        Pattern p = Pattern.compile(regexCode);
        Matcher matcher = p.matcher(pass);
        return matcher.matches();
    }

  
}
