/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlsv_swing.view;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author GIANG
 */
public class RegisterView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView1
     */
     
    public RegisterView() {
        initComponents();
        
          this.setVisible(false);
        // this.setLocationRelativeTo();
    }
     
    public void startLogin(){
          this.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        RegisterMainpanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        prevBtn = new javax.swing.JButton();
        reduceMouse = new javax.swing.JLabel();
        exitMouse = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        errUsername = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        confirmPassField = new javax.swing.JPasswordField();
        confirmPasswordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        errorPassword = new javax.swing.JTextField();
        errorConfirmPass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        RegisterMainpanel.setBackground(new java.awt.Color(255, 255, 255));
        RegisterMainpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegisterMainpanel.setForeground(new java.awt.Color(255, 255, 255));

        MainPanel.setBackground(new java.awt.Color(153, 255, 255));
        MainPanel.setForeground(new java.awt.Color(255, 255, 255));

        prevBtn.setBackground(new java.awt.Color(153, 255, 255));
        prevBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow_32px.png"))); // NOI18N
        prevBtn.setBorder(null);
        prevBtn.setBorderPainted(false);
        prevBtn.setContentAreaFilled(false);
        prevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prevBtn.setFocusPainted(false);
        prevBtn.setOpaque(true);
        prevBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prevBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prevBtnMouseExited(evt);
            }
        });
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });

        reduceMouse.setBackground(new java.awt.Color(153, 255, 255));
        reduceMouse.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reduceMouse.setText(" -");
        reduceMouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reduceMouse.setOpaque(true);
        reduceMouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reduceMouseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reduceMouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reduceMouseMouseExited(evt);
            }
        });

        exitMouse.setBackground(new java.awt.Color(153, 255, 255));
        exitMouse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitMouse.setText(" X");
        exitMouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitMouse.setOpaque(true);
        exitMouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(reduceMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(exitMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(prevBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(reduceMouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitMouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        usernameLabel.setText("Username");

        errUsername.setEditable(false);
        errUsername.setBackground(new java.awt.Color(255, 255, 255));
        errUsername.setForeground(new java.awt.Color(255, 0, 0));
        errUsername.setText("user error");
        errUsername.setBorder(null);

        passwordLabel.setText("Password");

        confirmPasswordLabel.setText("Confirm");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        errorPassword.setEditable(false);
        errorPassword.setBackground(new java.awt.Color(255, 255, 255));
        errorPassword.setForeground(new java.awt.Color(255, 0, 0));
        errorPassword.setText("pas error");
        errorPassword.setBorder(null);

        errorConfirmPass.setEditable(false);
        errorConfirmPass.setBackground(new java.awt.Color(255, 255, 255));
        errorConfirmPass.setForeground(new java.awt.Color(255, 0, 0));
        errorConfirmPass.setText("confirm error");
        errorConfirmPass.setBorder(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Register");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);

        javax.swing.GroupLayout RegisterMainpanelLayout = new javax.swing.GroupLayout(RegisterMainpanel);
        RegisterMainpanel.setLayout(RegisterMainpanelLayout);
        RegisterMainpanelLayout.setHorizontalGroup(
            RegisterMainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RegisterMainpanelLayout.createSequentialGroup()
                .addGroup(RegisterMainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterMainpanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(RegisterMainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel)
                            .addComponent(passwordLabel)
                            .addComponent(confirmPasswordLabel))
                        .addGap(58, 58, 58)
                        .addGroup(RegisterMainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField)
                            .addComponent(confirmPassField)
                            .addComponent(passwordField)
                            .addGroup(RegisterMainpanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(RegisterMainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errUsername)
                                    .addComponent(errorConfirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(errorPassword)))))
                    .addGroup(RegisterMainpanelLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegisterMainpanelLayout.setVerticalGroup(
            RegisterMainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterMainpanelLayout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(RegisterMainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(errUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterMainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegisterMainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterMainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterMainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
    
     this.dispose();
    }//GEN-LAST:event_prevBtnActionPerformed

    private void prevBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevBtnMouseEntered
      prevBtn.setBackground(new Color(204,255,255));
    }//GEN-LAST:event_prevBtnMouseEntered

    private void prevBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevBtnMouseExited
      prevBtn.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_prevBtnMouseExited

    private void reduceMouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduceMouseMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_reduceMouseMouseClicked

    private void reduceMouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduceMouseMouseEntered
        reduceMouse.setBackground(new Color(220,220,220));
         reduceMouse.setForeground(Color.WHITE);
    }//GEN-LAST:event_reduceMouseMouseEntered

    private void reduceMouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduceMouseMouseExited
        reduceMouse.setBackground(new Color(153,255,255));
         reduceMouse.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_reduceMouseMouseExited

    private void exitMouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMouseClicked
        
    }//GEN-LAST:event_exitMouseMouseClicked

    private void exitMouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMouseEntered
        exitMouse.setBackground(new Color(254,150,150));
                 exitMouse.setForeground(Color.WHITE);

    }//GEN-LAST:event_exitMouseMouseEntered

    private void exitMouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMouseExited
        exitMouse.setBackground(new Color(153,255,255));
                 exitMouse.setForeground(new Color(0,0,0));

    }//GEN-LAST:event_exitMouseMouseExited

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel RegisterMainpanel;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JTextField errUsername;
    private javax.swing.JTextField errorConfirmPass;
    private javax.swing.JTextField errorPassword;
    private javax.swing.JLabel exitMouse;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton prevBtn;
    private javax.swing.JLabel reduceMouse;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
